<a href="https://colab.research.google.com/github/lonehuntress/AeroSafe-AI/blob/main/colab/data_exploration_first.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# Chargement des module pour l'exploration des données
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
#from google.colab import files
#files.upload()

In [6]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

cp: cannot stat 'kaggle.json': No such file or directory
chmod: cannot access '/root/.kaggle/kaggle.json': No such file or directory

In [7]:
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle) (6.3.0)
Requirement already satisfied: jupytext in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.19.3)
Requirement already satisfied: kagglesdk<1.0,>=0.1.20 in /usr/local/lib/python3.12/dist-packages (from kaggle) (0.1.23)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kaggle) (26.2)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle) (5.29.6)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (4.2.0)
Requirement already satisfied: mdit-py-plugins in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (0.6.1)
Requirement already satisfied: nbformat in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (5.10.4)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (6.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.12/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.15)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (2026.5.20)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (5.7.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.30.0)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.9.6)
Requirement already satisfied: typing-extensions>=4.4.0 in /usr/local/lib/python3.12/dist-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat->jupytext->kaggle) (4.15.0)

In [8]:
!kaggle datasets download -d usdot/flight-delays

Dataset URL: https://www.kaggle.com/datasets/usdot/flight-delays
License(s): CC0-1.0
Downloading flight-delays.zip to /content
100% 191M/191M [00:01<00:00, 159MB/s]

In [9]:
import zipfile

with zipfile.ZipFile("flight-delays.zip", "r") as zip_ref:
    zip_ref.extractall("flight_data")

In [10]:
df1 = pd.read_csv("flight_data/flights.csv")
df2 = pd.read_csv("flight_data/airports.csv")
df3 = pd.read_csv("flight_data/airlines.csv")

/tmp/ipykernel_2370/3873058577.py:1: DtypeWarning: Columns (7,8) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv("flight_data/flights.csv")

In [11]:
df1.head()

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,...,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
0,2015,1,1,4,AS,98,N407AS,ANC,SEA,5,...,408.0,-22.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1,2015,1,1,4,AA,2336,N3KUAA,LAX,PBI,10,...,741.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
2,2015,1,1,4,US,840,N171US,SFO,CLT,20,...,811.0,5.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
3,2015,1,1,4,AA,258,N3HYAA,LAX,MIA,20,...,756.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,2015,1,1,4,AS,135,N527AS,SEA,ANC,25,...,259.0,-21.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df1.head()
df1.shape
df1.describe

<bound method NDFrame.describe of          YEAR  MONTH  DAY  DAY_OF_WEEK AIRLINE  FLIGHT_NUMBER TAIL_NUMBER  \
0        2015      1    1            4      AS             98      N407AS
1        2015      1    1            4      AA           2336      N3KUAA
2        2015      1    1            4      US            840      N171US
3        2015      1    1            4      AA            258      N3HYAA
4        2015      1    1            4      AS            135      N527AS
...       ...    ...  ...          ...     ...            ...         ...
5819074  2015     12   31            4      B6            688      N657JB
5819075  2015     12   31            4      B6            745      N828JB
5819076  2015     12   31            4      B6           1503      N913JB
5819077  2015     12   31            4      B6            333      N527JB
5819078  2015     12   31            4      B6            839      N534JB

        ORIGIN_AIRPORT DESTINATION_AIRPORT  SCHEDULED_DEPARTURE  ...  \
0                  ANC                 SEA                    5  ...
1                  LAX                 PBI                   10  ...
2                  SFO                 CLT                   20  ...
3                  LAX                 MIA                   20  ...
4                  SEA                 ANC                   25  ...
...                ...                 ...                  ...  ...
5819074            LAX                 BOS                 2359  ...
5819075            JFK                 PSE                 2359  ...
5819076            JFK                 SJU                 2359  ...
5819077            MCO                 SJU                 2359  ...
5819078            JFK                 BQN                 2359  ...

         ARRIVAL_TIME  ARRIVAL_DELAY  DIVERTED  CANCELLED  \
0               408.0          -22.0         0          0
1               741.0           -9.0         0          0
2               811.0            5.0         0          0
3               756.0           -9.0         0          0
4               259.0          -21.0         0          0
...               ...            ...       ...        ...
5819074         753.0          -26.0         0          0
5819075         430.0          -16.0         0          0
5819076         432.0           -8.0         0          0
5819077         330.0          -10.0         0          0
5819078         442.0            2.0         0          0

         CANCELLATION_REASON  AIR_SYSTEM_DELAY  SECURITY_DELAY  AIRLINE_DELAY  \
0                        NaN               NaN             NaN            NaN
1                        NaN               NaN             NaN            NaN
2                        NaN               NaN             NaN            NaN
3                        NaN               NaN             NaN            NaN
4                        NaN               NaN             NaN            NaN
...                      ...               ...             ...            ...
5819074                  NaN               NaN             NaN            NaN
5819075                  NaN               NaN             NaN            NaN
5819076                  NaN               NaN             NaN            NaN
5819077                  NaN               NaN             NaN            NaN
5819078                  NaN               NaN             NaN            NaN

         LATE_AIRCRAFT_DELAY  WEATHER_DELAY
0                        NaN            NaN
1                        NaN            NaN
2                        NaN            NaN
3                        NaN            NaN
4                        NaN            NaN
...                      ...            ...
5819074                  NaN            NaN
5819075                  NaN            NaN
5819076                  NaN            NaN
5819077                  NaN            NaN
5819078                  NaN            NaN

[5819079 rows x 31 columns]>

In [13]:
df1.isnull().sum()*100 / len(df1)

YEAR                    0.000000
MONTH                   0.000000
DAY                     0.000000
DAY_OF_WEEK             0.000000
AIRLINE                 0.000000
FLIGHT_NUMBER           0.000000
TAIL_NUMBER             0.252978
ORIGIN_AIRPORT          0.000000
DESTINATION_AIRPORT     0.000000
SCHEDULED_DEPARTURE     0.000000
DEPARTURE_TIME          1.480526
DEPARTURE_DELAY         1.480526
TAXI_OUT                1.530259
WHEELS_OFF              1.530259
SCHEDULED_TIME          0.000103
ELAPSED_TIME            1.805629
AIR_TIME                1.805629
DISTANCE                0.000000
WHEELS_ON               1.589822
TAXI_IN                 1.589822
SCHEDULED_ARRIVAL       0.000000
ARRIVAL_TIME            1.589822
ARRIVAL_DELAY           1.805629
DIVERTED                0.000000
CANCELLED               0.000000
CANCELLATION_REASON    98.455357
AIR_SYSTEM_DELAY       81.724960
SECURITY_DELAY         81.724960
AIRLINE_DELAY          81.724960
LATE_AIRCRAFT_DELAY    81.724960
WEATHER_DELAY          81.724960
dtype: float64

In [14]:
list_drop = ['FLIGHT_NUMBER', 'TAIL_NUMBER', 'AIRLINE', 'TAXI_OUT', 'TAXI_IN', 'WHEELS_OFF', 'WHEELS_ON', 'AIR_TIME', 'AIR_SYSTEM_DELAY', 'SECURITY_DELAY', 'AIRLINE_DELAY', 'LATE_AIRCRAFT_DELAY', 'WEATHER_DELAY', 'CANCELLED', 'CANCELLATION_REASON', 'DIVERTED']
i = 0
for i in range(0, len(list_drop)-1):
  df1.drop(list_drop[i], axis = 1, inplace = True)

In [15]:
df1.head()

,YEAR,MONTH,DAY,DAY_OF_WEEK,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,DEPARTURE_TIME,DEPARTURE_DELAY,SCHEDULED_TIME,ELAPSED_TIME,DISTANCE,SCHEDULED_ARRIVAL,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED
0,2015,1,1,4,ANC,SEA,5,2354.0,-11.0,205.0,194.0,1448,430,408.0,-22.0,0
1,2015,1,1,4,LAX,PBI,10,2.0,-8.0,280.0,279.0,2330,750,741.0,-9.0,0
2,2015,1,1,4,SFO,CLT,20,18.0,-2.0,286.0,293.0,2296,806,811.0,5.0,0
3,2015,1,1,4,LAX,MIA,20,15.0,-5.0,285.0,281.0,2342,805,756.0,-9.0,0
4,2015,1,1,4,SEA,ANC,25,24.0,-1.0,235.0,215.0,1448,320,259.0,-21.0,0

In [16]:
df1.isnull().sum()*100 / len(df1)

YEAR                   0.000000
MONTH                  0.000000
DAY                    0.000000
DAY_OF_WEEK            0.000000
ORIGIN_AIRPORT         0.000000
DESTINATION_AIRPORT    0.000000
SCHEDULED_DEPARTURE    0.000000
DEPARTURE_TIME         1.480526
DEPARTURE_DELAY        1.480526
SCHEDULED_TIME         0.000103
ELAPSED_TIME           1.805629
DISTANCE               0.000000
SCHEDULED_ARRIVAL      0.000000
ARRIVAL_TIME           1.589822
ARRIVAL_DELAY          1.805629
DIVERTED               0.000000
dtype: float64

In [17]:
df1.dropna(inplace = True)

In [18]:
df1.isnull().sum()*100 / len(df1)

YEAR                   0.0
MONTH                  0.0
DAY                    0.0
DAY_OF_WEEK            0.0
ORIGIN_AIRPORT         0.0
DESTINATION_AIRPORT    0.0
SCHEDULED_DEPARTURE    0.0
DEPARTURE_TIME         0.0
DEPARTURE_DELAY        0.0
SCHEDULED_TIME         0.0
ELAPSED_TIME           0.0
DISTANCE               0.0
SCHEDULED_ARRIVAL      0.0
ARRIVAL_TIME           0.0
ARRIVAL_DELAY          0.0
DIVERTED               0.0
dtype: float64

In [19]:
# Étape A: Transformer l'entier en chaîne de 4 caractères (ex: 730 devient "0730")
df1['TIME_STR'] = df1['SCHEDULED_DEPARTURE'].astype(str).str.zfill(4)

# Étape B: Isoler les heures et les minutes
df1['HOUR'] = df1['TIME_STR'].str[:2]
df1['MINUTE'] = df1['TIME_STR'].str[2:]

# Étape C: Créer une vraie colonne Datetime combinée
df1['FLIGHT_DATETIME'] = pd.to_datetime(
    df1['YEAR'].astype(str) + '-' +
    df1['MONTH'].astype(str) + '-' +
    df1['DAY'].astype(str) + ' ' +
    df1['HOUR'] + ':' + df1['MINUTE'] + ':00'
)

# Étape D: Supprimer les colonnes temporaires pour garder le dataset propre
df1 = df1.drop(columns=['TIME_STR', 'HOUR', 'MINUTE'])

In [20]:
df2.head()

,IATA_CODE,AIRPORT,CITY,STATE,COUNTRY,LATITUDE,LONGITUDE
0,ABE,Lehigh Valley International Airport,Allentown,PA,USA,40.65236,-75.44040
1,ABI,Abilene Regional Airport,Abilene,TX,USA,32.41132,-99.68190
2,ABQ,Albuquerque International Sunport,Albuquerque,NM,USA,35.04022,-106.60919
3,ABR,Aberdeen Regional Airport,Aberdeen,SD,USA,45.44906,-98.42183
4,ABY,Southwest Georgia Regional Airport,Albany,GA,USA,31.53552,-84.19447

In [21]:
df3.head()

  IATA_CODE                 AIRLINE
0        UA   United Air Lines Inc.
1        AA  American Airlines Inc.
2        US         US Airways Inc.
3        F9  Frontier Airlines Inc.
4        B6         JetBlue Airways

In [22]:
import requests

In [23]:
stations = {
    "ATL": "72219013874",
    "ORD": "72530094846",
    "DFW": "72259003927"
}

dfs = []

for airport, station in stations.items():

    url = f"https://www.ncei.noaa.gov/data/global-hourly/access/2015/{station}.csv"

    df = pd.read_csv(url)

    df["airport"] = airport

    dfs.append(df)

weather = pd.concat(dfs)

weather.head()

/tmp/ipykernel_2370/4196523493.py:13: DtypeWarning: Columns (43,44,48,53,57,68,69,89,98) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(url)
/tmp/ipykernel_2370/4196523493.py:13: DtypeWarning: Columns (36,45,56,88) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(url)
/tmp/ipykernel_2370/4196523493.py:13: DtypeWarning: Columns (42,43,44,45,49,54,58,59,92,101) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(url)

,STATION,DATE,SOURCE,LATITUDE,LONGITUDE,ELEVATION,NAME,REPORT_TYPE,CALL_SIGN,QUALITY_CONTROL,...,WA1,REM,EQD,airport,AL1,KA3,KA4,AT8,AX5,MV1
0,72219013874,2015-01-01T00:00:00,4,33.6301,-84.4418,307.8,ATLANTA HARTSFIELD JACKSON INTERNATIONAL AIRPO...,FM-12,99999,V020,...,NaN,SYN08072219 32966 43306 10061 20006 39903 4028...,NaN,ATL,NaN,NaN,NaN,NaN,NaN,NaN
1,72219013874,2015-01-01T00:52:00,7,33.6301,-84.4418,307.8,ATLANTA HARTSFIELD JACKSON INTERNATIONAL AIRPO...,FM-15,KATL,V030,...,NaN,MET10512/31/14 19:52:03 METAR KATL 010052Z 330...,D01 0ADE726,ATL,NaN,NaN,NaN,NaN,NaN,NaN
2,72219013874,2015-01-01T01:52:00,7,33.6301,-84.4418,307.8,ATLANTA HARTSFIELD JACKSON INTERNATIONAL AIRPO...,FM-15,KATL,V030,...,NaN,MET09812/31/14 20:52:03 METAR KATL 010152Z 310...,D01 0ADE726,ATL,NaN,NaN,NaN,NaN,NaN,NaN
3,72219013874,2015-01-01T02:52:00,7,33.6301,-84.4418,307.8,ATLANTA HARTSFIELD JACKSON INTERNATIONAL AIRPO...,FM-15,KATL,V030,...,NaN,MET10412/31/14 21:52:03 METAR KATL 010252Z 000...,D01 0ADE726,ATL,NaN,NaN,NaN,NaN,NaN,NaN
4,72219013874,2015-01-01T03:52:00,7,33.6301,-84.4418,307.8,ATLANTA HARTSFIELD JACKSON INTERNATIONAL AIRPO...,FM-15,KATL,V030,...,NaN,MET09912/31/14 22:52:03 METAR KATL 010352Z 320...,D01 0ADE726,ATL,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
weather.to_csv("weather_2015.csv", index=False)

In [27]:
weather.columns

Index(['STATION', 'DATE', 'SOURCE', 'LATITUDE', 'LONGITUDE', 'ELEVATION',
       'NAME', 'REPORT_TYPE', 'CALL_SIGN', 'QUALITY_CONTROL',
       ...
       'WA1', 'REM', 'EQD', 'airport', 'AL1', 'KA3', 'KA4', 'AT8', 'AX5',
       'MV1'],
      dtype='object', length=108)

# Garder uniquement les colonnes utiles

In [28]:
weather = weather[
    [
        "DATE",
        "WND",
        "VIS",
        "TMP",
        "DEW",
        "AA1"
    ]
].copy()

# Supression des doublons

In [29]:
weather.drop_duplicates(inplace=True)

# Gérer les valeurs manquantes

In [30]:
weather.replace(["9999", "99999", "999999"], pd.NA, inplace=True)

weather.dropna(inplace=True)

# Convertir la date

In [31]:
weather["DATE"] = pd.to_datetime(weather["DATE"])

weather["YEAR"] = weather["DATE"].dt.year
weather["MONTH"] = weather["DATE"].dt.month
weather["DAY"] = weather["DATE"].dt.day
weather["HOUR"] = weather["DATE"].dt.hour

# Extraire la visibilité

In [32]:
weather["VISIBILITY"] = (
    weather["VIS"]
    .str.split(",")
    .str[0]
    .astype(float)
)

# Extraire le vent

In [33]:
weather["WIND_SPEED"] = (
    weather["WND"]
    .str.split(",")
    .str[3]
    .astype(float)
)

# Extraire la température

In [34]:
weather["TEMPERATURE"] = (
    weather["TMP"]
    .str.split(",")
    .str[0]
    .astype(float)
    / 10
)

# Extraire les précipitations

In [35]:
weather["PRECIPITATION"] = (
    weather["AA1"]
    .fillna("00,0000,1,1")
    .str.split(",")
    .str[1]
    .astype(float)
)

# Garder uniquement les colonnes finales

In [36]:
weather_clean = weather[
    [
        "YEAR",
        "MONTH",
        "DAY",
        "HOUR",
        "VISIBILITY",
        "WIND_SPEED",
        "TEMPERATURE",
        "PRECIPITATION"
    ]
]

In [37]:
weather_clean.info()

weather_clean.head()

weather_clean.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 32309 entries, 1 to 14243
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   YEAR           32309 non-null  int32
 1   MONTH          32309 non-null  int32
 2   DAY            32309 non-null  int32
 3   HOUR           32309 non-null  int32
 4   VISIBILITY     32309 non-null  float64
 5   WIND_SPEED     32309 non-null  float64
 6   TEMPERATURE    32309 non-null  float64
 7   PRECIPITATION  32309 non-null  float64
dtypes: float64(4), int32(4)
memory usage: 1.7 MB

,YEAR,MONTH,DAY,HOUR,VISIBILITY,WIND_SPEED,TEMPERATURE,PRECIPITATION
count,32309.0,32309.000000,32309.000000,32309.000000,32309.000000,32309.000000,32309.00000,32309.000000
mean,2015.0,6.463400,15.866105,11.294005,43142.215203,339.638677,44.68788,6.280727
std,0.0,3.496766,8.877973,6.882493,167867.536814,1695.054562,167.94353,32.799983
min,2015.0,1.000000,1.000000,0.000000,0.000000,0.000000,-22.20000,0.000000
25%,2015.0,3.000000,8.000000,5.000000,14484.000000,26.000000,8.30000,0.000000
50%,2015.0,6.000000,16.000000,11.000000,16093.000000,41.000000,17.80000,0.000000
75%,2015.0,10.000000,24.000000,17.000000,16093.000000,57.000000,23.90000,0.000000
max,2015.0,12.000000,31.000000,23.000000,999999.000000,9999.000000,999.90000,998.000000

In [38]:
weather.columns.tolist()

['DATE',
 'WND',
 'VIS',
 'TMP',
 'DEW',
 'AA1',
 'YEAR',
 'MONTH',
 'DAY',
 'HOUR',
 'VISIBILITY',
 'WIND_SPEED',
 'TEMPERATURE',
 'PRECIPITATION']

sauvegarde

In [39]:
weather_clean.to_csv(
    "weather_2015_clean.csv",
    index=False
)

In [40]:
flights = pd.read_csv("dataset_fly_aero.csv")

print(flights.shape)
weather = pd.read_csv("weather_2015_clean.csv")

print(weather.shape)

(1590916, 16)
(32309, 8)

In [41]:
print(flights.columns.tolist())

['YEAR', 'MONTH', 'DAY', 'DAY_OF_WEEK', 'ORIGIN_AIRPORT', 'DESTINATION_AIRPORT', 'SCHEDULED_DEPARTURE', 'DEPARTURE_TIME', 'DEPARTURE_DELAY', 'SCHEDULED_TIME', 'ELAPSED_TIME', 'DISTANCE', 'SCHEDULED_ARRIVAL', 'ARRIVAL_TIME', 'ARRIVAL_DELAY', 'FLIGHT_DATETIME']

In [42]:
print(flights.columns.tolist())

['YEAR', 'MONTH', 'DAY', 'DAY_OF_WEEK', 'ORIGIN_AIRPORT', 'DESTINATION_AIRPORT', 'SCHEDULED_DEPARTURE', 'DEPARTURE_TIME', 'DEPARTURE_DELAY', 'SCHEDULED_TIME', 'ELAPSED_TIME', 'DISTANCE', 'SCHEDULED_ARRIVAL', 'ARRIVAL_TIME', 'ARRIVAL_DELAY', 'FLIGHT_DATETIME']

Il faut créer une colonne HOUR

In [43]:
flights["SCHEDULED_DEPARTURE"] = flights["SCHEDULED_DEPARTURE"].astype(str).str.zfill(4)

flights["HOUR"] = (
    flights["SCHEDULED_DEPARTURE"]
    .str[:2]
    .astype(int)
)

ValueError: invalid literal for int() with base 10: '0n'

In [44]:
flights[
    ~flights["SCHEDULED_DEPARTURE"]
    .astype(str)
    .str.match(r'^\d+$', na=False)
]["SCHEDULED_DEPARTURE"].unique()

array(['05.0', '10.0', '20.0', ..., '2326.0', '512.0', '0nan'],
      dtype=object)

In [45]:
mask = ~flights["SCHEDULED_DEPARTURE"].astype(str).str.match(r'^\d+$', na=False)

print(mask.sum())

1590916

In [46]:
flights["SCHEDULED_DEPARTURE"] = pd.to_numeric(
    flights["SCHEDULED_DEPARTURE"],
    errors="coerce"
)

In [47]:
flights = flights.dropna(subset=["SCHEDULED_DEPARTURE"])

In [48]:
flights["SCHEDULED_DEPARTURE"] = (
    flights["SCHEDULED_DEPARTURE"]
    .astype(int)
    .astype(str)
    .str.zfill(4)
)

flights["HOUR"] = (
    flights["SCHEDULED_DEPARTURE"]
    .str[:2]
    .astype(int)
)

In [49]:
print(flights["HOUR"].min())
print(flights["HOUR"].max())

0
23

In [50]:
flights[
    ~flights["SCHEDULED_DEPARTURE"]
    .astype(str)
    .str.match(r'^\d+$', na=False)
]["SCHEDULED_DEPARTURE"].unique()

array([], dtype=object)

In [51]:
flights[["SCHEDULED_DEPARTURE", "HOUR"]].head()

  SCHEDULED_DEPARTURE  HOUR
0                0005     0
1                0010     0
2                0020     0
3                0020     0
4                0025     0

In [52]:
print(weather.columns.tolist())

['YEAR', 'MONTH', 'DAY', 'HOUR', 'VISIBILITY', 'WIND_SPEED', 'TEMPERATURE', 'PRECIPITATION']

In [53]:
sample = flights.head(10000)

test_merge = pd.merge(
    sample,
    weather,
    on=["YEAR", "MONTH", "DAY", "HOUR"],
    how="left"
)

print(test_merge.shape)
test_merge.head()

(45009, 21)

,YEAR,MONTH,DAY,DAY_OF_WEEK,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,DEPARTURE_TIME,DEPARTURE_DELAY,SCHEDULED_TIME,...,DISTANCE,SCHEDULED_ARRIVAL,ARRIVAL_TIME,ARRIVAL_DELAY,FLIGHT_DATETIME,HOUR,VISIBILITY,WIND_SPEED,TEMPERATURE,PRECIPITATION
0,2015,1.0,1.0,4.0,ANC,SEA,0005,2354.0,-11.0,205.0,...,1448.0,430.0,408.0,-22.0,2015-01-01 00:05:00,0,16093.0,26.0,5.0,0.0
1,2015,1.0,1.0,4.0,ANC,SEA,0005,2354.0,-11.0,205.0,...,1448.0,430.0,408.0,-22.0,2015-01-01 00:05:00,0,16093.0,57.0,-7.8,0.0
2,2015,1.0,1.0,4.0,ANC,SEA,0005,2354.0,-11.0,205.0,...,1448.0,430.0,408.0,-22.0,2015-01-01 00:05:00,0,16093.0,41.0,0.6,0.0
3,2015,1.0,1.0,4.0,LAX,PBI,0010,2.0,-8.0,280.0,...,2330.0,750.0,741.0,-9.0,2015-01-01 00:10:00,0,16093.0,26.0,5.0,0.0
4,2015,1.0,1.0,4.0,LAX,PBI,0010,2.0,-8.0,280.0,...,2330.0,750.0,741.0,-9.0,2015-01-01 00:10:00,0,16093.0,57.0,-7.8,0.0

In [54]:
print(
    test_merge[
        ["VISIBILITY", "WIND_SPEED"]
    ].isna().mean() * 100
)

VISIBILITY    0.0
WIND_SPEED    0.0
dtype: float64

In [55]:
dataset_final = pd.merge(
    flights,
    weather,
    on=["YEAR", "MONTH", "DAY", "HOUR"],
    how="left"
)

In [56]:
print(dataset_final.shape)

(6096758, 21)

In [57]:
dataset_final.to_csv(
    "dataset_final_aerosafe.csv",
    index=False
)

In [58]:
def create_risk(row):

    if row["VISIBILITY"] < 2000:
        return "Rouge"

    elif row["WIND_SPEED"] > 50:
        return "Orange"

    elif row["DEPARTURE_DELAY"] > 60:
        return "Orange"

    else:
        return "Vert"

In [59]:
dataset_final["RISK_LEVEL"] = dataset_final.apply(
    create_risk,
    axis=1
)

In [60]:
print(dataset_final.shape)

dataset_final.head()

dataset_final["RISK_LEVEL"].value_counts()

(6096758, 22)

RISK_LEVEL
Vert      3271427
Orange    2425920
Rouge      399411
Name: count, dtype: int64

In [61]:
dataset_final.to_csv(
    "dataset_final_aerosafe.csv",
    index=False
)

In [64]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [70]:
dataset_final.to_csv(
    "/content/drive/MyDrive/AeroSafeAI/dataset_final_aerosafe.csv",
    index=False
)