<a href="https://colab.research.google.com/github/lonehuntress/AeroSafe-AI/blob/main/colab/data_exploration_first.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# Chargement des module pour l'exploration des données
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
#from google.colab import files
#files.upload()

In [6]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

cp: cannot stat 'kaggle.json': No such file or directory
chmod: cannot access '/root/.kaggle/kaggle.json': No such file or directory

In [7]:
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle) (6.3.0)
Requirement already satisfied: jupytext in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.19.1)
Requirement already satisfied: kagglesdk<1.0,>=0.1.20 in /usr/local/lib/python3.12/dist-packages (from kaggle) (0.1.20)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kaggle) (26.1)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle) (5.29.6)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (4.0.0)
Requirement already satisfied: mdit-py-plugins in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (0.5.0)
Requirement already satisfied: nbformat in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (5.10.4)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (6.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.12/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.13)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (2026.4.22)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (5.7.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.30.0)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.9.6)
Requirement already satisfied: typing-extensions>=4.4.0 in /usr/local/lib/python3.12/dist-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat->jupytext->kaggle) (4.15.0)

In [8]:
!kaggle datasets download -d usdot/flight-delays

Dataset URL: https://www.kaggle.com/datasets/usdot/flight-delays
License(s): CC0-1.0
Downloading flight-delays.zip to /content
100% 191M/191M [00:01<00:00, 102MB/s]

In [9]:
import zipfile

with zipfile.ZipFile("flight-delays.zip", "r") as zip_ref:
    zip_ref.extractall("flight_data")

In [10]:
df1 = pd.read_csv("flight_data/flights.csv")
df2 = pd.read_csv("flight_data/airports.csv")
df3 = pd.read_csv("flight_data/airlines.csv")

/tmp/ipykernel_1070/3873058577.py:1: DtypeWarning: Columns (7,8) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv("flight_data/flights.csv")

In [11]:
df1.head()

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,...,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
0,2015,1,1,4,AS,98,N407AS,ANC,SEA,5,...,408.0,-22.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1,2015,1,1,4,AA,2336,N3KUAA,LAX,PBI,10,...,741.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
2,2015,1,1,4,US,840,N171US,SFO,CLT,20,...,811.0,5.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
3,2015,1,1,4,AA,258,N3HYAA,LAX,MIA,20,...,756.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,2015,1,1,4,AS,135,N527AS,SEA,ANC,25,...,259.0,-21.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
df1.head()
df1.shape
df1.describe

<bound method NDFrame.describe of          YEAR  MONTH  DAY  DAY_OF_WEEK ORIGIN_AIRPORT DESTINATION_AIRPORT  \
0        2015      1    1            4            ANC                 SEA
1        2015      1    1            4            LAX                 PBI
2        2015      1    1            4            SFO                 CLT
3        2015      1    1            4            LAX                 MIA
4        2015      1    1            4            SEA                 ANC
...       ...    ...  ...          ...            ...                 ...
5819074  2015     12   31            4            LAX                 BOS
5819075  2015     12   31            4            JFK                 PSE
5819076  2015     12   31            4            JFK                 SJU
5819077  2015     12   31            4            MCO                 SJU
5819078  2015     12   31            4            JFK                 BQN

         SCHEDULED_DEPARTURE  DEPARTURE_TIME  DEPARTURE_DELAY  SCHEDULED_TIME  \
0                          5          2354.0            -11.0           205.0
1                         10             2.0             -8.0           280.0
2                         20            18.0             -2.0           286.0
3                         20            15.0             -5.0           285.0
4                         25            24.0             -1.0           235.0
...                      ...             ...              ...             ...
5819074                 2359          2355.0             -4.0           320.0
5819075                 2359          2355.0             -4.0           227.0
5819076                 2359          2350.0             -9.0           221.0
5819077                 2359          2353.0             -6.0           161.0
5819078                 2359            14.0             15.0           221.0

         ELAPSED_TIME  DISTANCE  SCHEDULED_ARRIVAL  ARRIVAL_TIME  \
0               194.0      1448                430         408.0
1               279.0      2330                750         741.0
2               293.0      2296                806         811.0
3               281.0      2342                805         756.0
4               215.0      1448                320         259.0
...               ...       ...                ...           ...
5819074         298.0      2611                819         753.0
5819075         215.0      1617                446         430.0
5819076         222.0      1598                440         432.0
5819077         157.0      1189                340         330.0
5819078         208.0      1576                440         442.0

         ARRIVAL_DELAY
0                -22.0
1                 -9.0
2                  5.0
3                 -9.0
4                -21.0
...                ...
5819074          -26.0
5819075          -16.0
5819076           -8.0
5819077          -10.0
5819078            2.0

[5819079 rows x 15 columns]>

In [13]:
df1.isnull().sum()*100 / len(df1)

YEAR                    0.000000
MONTH                   0.000000
DAY                     0.000000
DAY_OF_WEEK             0.000000
AIRLINE                 0.000000
FLIGHT_NUMBER           0.000000
TAIL_NUMBER             0.252978
ORIGIN_AIRPORT          0.000000
DESTINATION_AIRPORT     0.000000
SCHEDULED_DEPARTURE     0.000000
DEPARTURE_TIME          1.480526
DEPARTURE_DELAY         1.480526
TAXI_OUT                1.530259
WHEELS_OFF              1.530259
SCHEDULED_TIME          0.000103
ELAPSED_TIME            1.805629
AIR_TIME                1.805629
DISTANCE                0.000000
WHEELS_ON               1.589822
TAXI_IN                 1.589822
SCHEDULED_ARRIVAL       0.000000
ARRIVAL_TIME            1.589822
ARRIVAL_DELAY           1.805629
DIVERTED                0.000000
CANCELLED               0.000000
CANCELLATION_REASON    98.455357
AIR_SYSTEM_DELAY       81.724960
SECURITY_DELAY         81.724960
AIRLINE_DELAY          81.724960
LATE_AIRCRAFT_DELAY    81.724960
WEATHER_DELAY          81.724960
dtype: float64

In [17]:
list_drop = ['FLIGHT_NUMBER', 'TAIL_NUMBER', 'AIRLINE', 'TAXI_OUT', 'TAXI_IN', 'WHEELS_OFF', 'WHEELS_ON', 'AIR_TIME', 'AIR_SYSTEM_DELAY', 'SECURITY_DELAY', 'AIRLINE_DELAY', 'LATE_AIRCRAFT_DELAY', 'WEATHER_DELAY', 'CANCELLED', 'CANCELLATION_REASON', 'DIVERTED']
i = 0
for i in range(0, len(list_drop)-1):
  df1.drop(list_drop[i], axis = 1, inplace = True)

In [29]:
df1.head()

,YEAR,MONTH,DAY,DAY_OF_WEEK,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,DEPARTURE_TIME,DEPARTURE_DELAY,SCHEDULED_TIME,ELAPSED_TIME,DISTANCE,SCHEDULED_ARRIVAL,ARRIVAL_TIME,ARRIVAL_DELAY,FLIGHT_DATETIME
0,2015,1,1,4,ANC,SEA,5,2354.0,-11.0,205.0,194.0,1448,430,408.0,-22.0,2015-01-01 00:05:00
1,2015,1,1,4,LAX,PBI,10,2.0,-8.0,280.0,279.0,2330,750,741.0,-9.0,2015-01-01 00:10:00
2,2015,1,1,4,SFO,CLT,20,18.0,-2.0,286.0,293.0,2296,806,811.0,5.0,2015-01-01 00:20:00
3,2015,1,1,4,LAX,MIA,20,15.0,-5.0,285.0,281.0,2342,805,756.0,-9.0,2015-01-01 00:20:00
4,2015,1,1,4,SEA,ANC,25,24.0,-1.0,235.0,215.0,1448,320,259.0,-21.0,2015-01-01 00:25:00

In [20]:
df1.isnull().sum()*100 / len(df1)

YEAR                   0.000000
MONTH                  0.000000
DAY                    0.000000
DAY_OF_WEEK            0.000000
ORIGIN_AIRPORT         0.000000
DESTINATION_AIRPORT    0.000000
SCHEDULED_DEPARTURE    0.000000
DEPARTURE_TIME         1.480526
DEPARTURE_DELAY        1.480526
SCHEDULED_TIME         0.000103
ELAPSED_TIME           1.805629
DISTANCE               0.000000
SCHEDULED_ARRIVAL      0.000000
ARRIVAL_TIME           1.589822
ARRIVAL_DELAY          1.805629
dtype: float64

In [24]:
df1.dropna(inplace = True)

In [28]:
df1.isnull().sum()*100 / len(df1)

YEAR                   0.0
MONTH                  0.0
DAY                    0.0
DAY_OF_WEEK            0.0
ORIGIN_AIRPORT         0.0
DESTINATION_AIRPORT    0.0
SCHEDULED_DEPARTURE    0.0
DEPARTURE_TIME         0.0
DEPARTURE_DELAY        0.0
SCHEDULED_TIME         0.0
ELAPSED_TIME           0.0
DISTANCE               0.0
SCHEDULED_ARRIVAL      0.0
ARRIVAL_TIME           0.0
ARRIVAL_DELAY          0.0
FLIGHT_DATETIME        0.0
dtype: float64

In [27]:
# Étape A: Transformer l'entier en chaîne de 4 caractères (ex: 730 devient "0730")
df1['TIME_STR'] = df1['SCHEDULED_DEPARTURE'].astype(str).str.zfill(4)

# Étape B: Isoler les heures et les minutes
df1['HOUR'] = df1['TIME_STR'].str[:2]
df1['MINUTE'] = df1['TIME_STR'].str[2:]

# Étape C: Créer une vraie colonne Datetime combinée
df1['FLIGHT_DATETIME'] = pd.to_datetime(
    df1['YEAR'].astype(str) + '-' +
    df1['MONTH'].astype(str) + '-' +
    df1['DAY'].astype(str) + ' ' +
    df1['HOUR'] + ':' + df1['MINUTE'] + ':00'
)

# Étape D: Supprimer les colonnes temporaires pour garder le dataset propre
df1 = df1.drop(columns=['TIME_STR', 'HOUR', 'MINUTE'])

In [30]:
df2.head()

,IATA_CODE,AIRPORT,CITY,STATE,COUNTRY,LATITUDE,LONGITUDE
0,ABE,Lehigh Valley International Airport,Allentown,PA,USA,40.65236,-75.44040
1,ABI,Abilene Regional Airport,Abilene,TX,USA,32.41132,-99.68190
2,ABQ,Albuquerque International Sunport,Albuquerque,NM,USA,35.04022,-106.60919
3,ABR,Aberdeen Regional Airport,Aberdeen,SD,USA,45.44906,-98.42183
4,ABY,Southwest Georgia Regional Airport,Albany,GA,USA,31.53552,-84.19447