<a href="https://colab.research.google.com/github/lonehuntress/AeroSafe-AI/blob/main/colab/preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [50]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [51]:
import pandas as pd

df = pd.read_csv(
    "/content/drive/MyDrive/AeroSafeAI/dataset_final_aerosafe.csv"
)

In [52]:
df.isnull().sum()

YEAR                   0
MONTH                  0
DAY                    0
DAY_OF_WEEK            0
ORIGIN_AIRPORT         0
DESTINATION_AIRPORT    0
SCHEDULED_DEPARTURE    0
DEPARTURE_TIME         0
DEPARTURE_DELAY        0
SCHEDULED_TIME         0
ELAPSED_TIME           0
DISTANCE               0
SCHEDULED_ARRIVAL      0
ARRIVAL_TIME           0
ARRIVAL_DELAY          0
FLIGHT_DATETIME        0
HOUR                   0
VISIBILITY             0
WIND_SPEED             0
TEMPERATURE            0
PRECIPITATION          0
RISK_LEVEL             0
dtype: int64

In [53]:
df['RISK_LEVEL']

0            Vert
1          Orange
2            Vert
3            Vert
4          Orange
            ...
6096753      Vert
6096754      Vert
6096755      Vert
6096756    Orange
6096757      Vert
Name: RISK_LEVEL, Length: 6096758, dtype: object

In [54]:
print(df["RISK_LEVEL"].value_counts())

RISK_LEVEL
Vert      3271427
Orange    2425920
Rouge      399411
Name: count, dtype: int64

In [55]:
import numpy as np

df["RISK_LEVEL"] = np.where(
    df["DEPARTURE_DELAY"] > 15,
    1,
    0
)
df = df.drop(
    columns=[
        "FLIGHT_DATETIME"
    ],
    errors="ignore"
)
from sklearn.preprocessing import LabelEncoder

le_origin = LabelEncoder()
le_dest = LabelEncoder()

df["ORIGIN_AIRPORT"] = le_origin.fit_transform(df["ORIGIN_AIRPORT"])

df["DESTINATION_AIRPORT"] = le_dest.fit_transform(
    df["DESTINATION_AIRPORT"]
)

In [56]:
X = df.drop(
    columns=[
        "RISK_LEVEL",
        "DEPARTURE_DELAY",
        "ARRIVAL_DELAY",
        "DEPARTURE_TIME",
        "ARRIVAL_TIME"
    ]
)

y = df["RISK_LEVEL"]

In [57]:
print(X.columns.tolist())
print(y.head())

['YEAR', 'MONTH', 'DAY', 'DAY_OF_WEEK', 'ORIGIN_AIRPORT', 'DESTINATION_AIRPORT', 'SCHEDULED_DEPARTURE', 'SCHEDULED_TIME', 'ELAPSED_TIME', 'DISTANCE', 'SCHEDULED_ARRIVAL', 'HOUR', 'VISIBILITY', 'WIND_SPEED', 'TEMPERATURE', 'PRECIPITATION']
0    0
1    0
2    0
3    0
4    0
Name: RISK_LEVEL, dtype: int64

# données

In [58]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [59]:
# X_train.to_csv("X_train.csv", index=False)
# X_test.to_csv("X_test.csv", index=False)

# y_train.to_csv("y_train.csv", index=False)
# y_test.to_csv("y_test.csv", index=False)

In [60]:
X_train.to_csv("/content/drive/MyDrive/AeroSafeAI/X_train.csv", index=False)
X_test.to_csv("/content/drive/MyDrive/AeroSafeAI/X_test.csv", index=False)

y_train.to_csv("/content/drive/MyDrive/AeroSafeAI/y_train.csv", index=False)
y_test.to_csv("/content/drive/MyDrive/AeroSafeAI/y_test.csv", index=False)