<a href="https://colab.research.google.com/github/lonehuntress/AeroSafe-AI/blob/main/colab/preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

df = pd.read_csv(
    "/content/drive/MyDrive/AeroSafeAI/dataset_final_aerosafe.csv"
)

In [3]:
df.isnull().sum()

YEAR                   0
MONTH                  0
DAY                    0
DAY_OF_WEEK            0
ORIGIN_AIRPORT         0
DESTINATION_AIRPORT    0
SCHEDULED_DEPARTURE    0
DEPARTURE_TIME         0
DEPARTURE_DELAY        0
SCHEDULED_TIME         0
ELAPSED_TIME           0
DISTANCE               0
SCHEDULED_ARRIVAL      0
ARRIVAL_TIME           0
ARRIVAL_DELAY          0
FLIGHT_DATETIME        0
HOUR                   0
VISIBILITY             0
WIND_SPEED             0
TEMPERATURE            0
PRECIPITATION          0
RISK_LEVEL             0
dtype: int64

In [10]:
df['RISK_LEVEL']

0            Vert
1          Orange
2            Vert
3            Vert
4          Orange
            ...
6096753      Vert
6096754      Vert
6096755      Vert
6096756    Orange
6096757      Vert
Name: RISK_LEVEL, Length: 6096758, dtype: object

In [11]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False)

encoded = encoder.fit_transform(df[["RISK_LEVEL"]])

In [12]:
X = df.drop(
    columns=["RISK_LEVEL"]
)

y = df["RISK_LEVEL"]